name: 'test AWS Access'

# The workflow should only trigger manually
on:
  workflow_dispatch:

# Required to get the ID Token that will be used for OIDC
permissions:
  id-token: write
  contents: read # needed for private repos to checkout

jobs:
  aws:
    runs-on: ubuntu-latest
    steps:
      - name: Generate OIDC Token
        run: echo "OIDC_TOKEN_VALUE" > oidc_token.txt

      - name: Check OIDC Token Subject
        run: |
          token_subject=$(jq -r '.sub' oidc_token.txt)
          if [[ $token_subject =~ ^repo:.*\/hacktricks-training.*$ ]]; then
            echo "Token subject matches the pattern."
          else
            echo "Token subject does not match the pattern."
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::036557995396:role/sts-lab-2-target
          role-session-name: OIDCSession

      - run: aws sts get-caller-identity
        shell: bash
